### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by Laffery** [fengxinhhh/Cimi#11]
不懂就问，git replase是啥

以及，感觉发包其实就那么几个命令，可以自己写个shell完成，cimi除了可交互还有别的优势吗

**Comment by fengxinhhh** [comment]
![image](https://user-images.githubusercontent.com/78004597/196637063-932c0806-9beb-4e1b-b270-d8d42c7d49e5.png)
如果是看的这个地方的话，应该是写错了，这一个地方想表达的意思是git add、git commit、git push。

然后cimi的最早的用处是我给concis发npm包用的，本质其实就是把一大堆终端操作合并到一句命令的node脚本，功能目前比较少，有新的想法欢迎提出来~

**Comment by Laffery** [comment]
okk,还有一个问题，比如现在很多项目在git commit的时候，会跑lint-stage，如果check失败，cimi还能继续下去吗？还有lint-stage里面的eslint --fix，自动修复修改了文件，这部分变更能add上吗

**Comment by fengxinhhh** [comment]
关于pre-commit，这个问题其实cimi只是一步一步在终端执行命令，如果某一步挂了肯定会err code 1退出的。
如果格式化修复了，也会修复完自己推送上去的，其实就是把手动的步骤自动化了，省去了你等待、打命令的时间，我正好patch了一下concis，看一下这个截图吧。

![image](https://user-images.githubusercontent.com/78004597/196700705-0f2d13b5-eee7-4978-8395-e5602d354880.png)

**Comment by fengxinhhh** [comment]
一步步的，很明显。

**Comment by Laffery** [comment]
LGTM
